// @generated by lenso-contract-codegen; do not edit.
use std::{fmt, rc::Rc};
use futures::future::LocalBoxFuture;
use lenso_kernel::{InvocationContext, NativeRequestEndpoint, NativeRequestFuture, NativeRequestHandle, PluginDependencies, RequestCapability, RuntimeFailure};

use lenso_plugin_authoring::{BoundCapabilityClient, CapabilityClient, CapabilityClientMany};
pub const CAPABILITY_ID: &str = "lenso.organization-membership@1";
pub const DESCRIPTOR_VERSION: &str = "1.0.0";
pub const PORTABLE: bool = true;
pub const CROSS_LANE_TRANSFER: bool = true;
pub const ORGANIZATION_MEMBERSHIP_CAPABILITY_ID: &str = CAPABILITY_ID;
pub const ORGANIZATION_MEMBERSHIP_DESCRIPTOR_VERSION: &str = DESCRIPTOR_VERSION;

#[doc(hidden)]
#[macro_export]
macro_rules! __lenso_provided_organization_membership { () => { "{\"capability_id\":\"lenso.organization-membership@1\",\"descriptor_version\":\"1.0.0\",\"operations\":[\"check_membership\"],\"operation_kinds\":{},\"default_admission\":{\"queue_capacity\":0,\"max_concurrency\":1},\"operation_admissions\":{},\"event_admission\":null,\"cross_lane_transfer\":true}" }; }

#[doc(hidden)]
#[macro_export]
macro_rules! __lenso_required_organization_membership_client { () => { "{\"capability_id\":\"lenso.organization-membership@1\",\"descriptor_version\":\"1.0.0\",\"cardinality\":\"one\"}" }; }

#[doc(hidden)]
#[macro_export]
macro_rules! __lenso_required_many_organization_membership_client { () => { "{\"capability_id\":\"lenso.organization-membership@1\",\"descriptor_version\":\"1.0.0\",\"cardinality\":\"many\"}" }; }

pub const CHECK_MEMBERSHIP_OPERATION: &str = "check_membership";

pub use lenso_contract_runtime::{UnknownDomainError};
use lenso_contract_runtime::{decode_portable_json, encode_portable_json};

#[derive(Clone, Debug, PartialEq, serde::Serialize, serde::Deserialize)]
pub struct CheckMembershipRequest {
    #[serde(rename = "organization_id")]
    #[serde(deserialize_with = "lenso_contract_runtime::serde::deserialize_required")]
    pub organization_id: String,
    #[serde(rename = "subject")]
    #[serde(deserialize_with = "lenso_contract_runtime::serde::deserialize_required")]
    pub subject: String,
}

#[derive(Clone, Debug, PartialEq, serde::Serialize, serde::Deserialize)]
pub struct CheckMembershipResponse {
    #[serde(rename = "active")]
    #[serde(deserialize_with = "lenso_contract_runtime::serde::deserialize_required")]
    pub active: bool,
    #[serde(rename = "owner")]
    #[serde(deserialize_with = "lenso_contract_runtime::serde::deserialize_required")]
    pub owner: bool,
}

#[derive(Clone, Debug, PartialEq)]
pub enum CheckMembershipError {
    InvalidRequest,
    OrganizationNotFound,
    Unknown(UnknownDomainError),
}

#[derive(Debug)]
pub struct OrganizationMembership;
impl RequestCapability for OrganizationMembership {
    type Request = CheckMembershipRequest;
    type Response = CheckMembershipResponse;
    type DomainError = CheckMembershipError;
    const ID: &'static str = CAPABILITY_ID;
    const DESCRIPTOR_VERSION: &'static str = DESCRIPTOR_VERSION;

    fn invoke_native(endpoint: &dyn NativeRequestEndpoint, operation: &str, request: Self::Request, context: InvocationContext) -> NativeRequestFuture<Self> {
        if operation != CHECK_MEMBERSHIP_OPERATION {
            return lenso_kernel::invoke_typed_or_erased_native_request::<Self>(endpoint, operation, request, context);
        }
        let Some(typed_endpoint) = endpoint
            .typed_endpoint()
            .and_then(|endpoint| endpoint.downcast_ref::<OrganizationMembershipRequestEndpoint>())
        else {
            return lenso_kernel::invoke_typed_or_erased_native_request::<Self>(endpoint, operation, request, context);
        };
        Rc::clone(&typed_endpoint.provider).check_membership(context, request)
    }
}

impl serde::Serialize for CheckMembershipError {
    fn serialize<S>(&self, serializer: S) -> Result<S::Ok, S::Error>
    where
        S: serde::Serializer,
    {
        use serde::ser::SerializeMap;
        match self {
            Self::InvalidRequest => serializer.serialize_str("invalid_request"),
            Self::OrganizationNotFound => serializer.serialize_str("organization_not_found"),
            Self::Unknown(value) => {
                let mut map = serializer.serialize_map(Some(1 + usize::from(value.payload.is_some()) + value.extra.len()))?;
                map.serialize_entry("code", &value.code)?;
                if let Some(payload) = &value.payload {
                    map.serialize_entry("payload", payload)?;
                }
                for (key, extra) in &value.extra {
                    map.serialize_entry(key, extra)?;
                }
                map.end()
            },
        }
    }
}

impl<'de> serde::Deserialize<'de> for CheckMembershipError {
    fn deserialize<D>(deserializer: D) -> Result<Self, D::Error>
    where
        D: serde::Deserializer<'de>,
    {
        let value = <serde_json::Value as serde::Deserialize>::deserialize(deserializer)?;
        match value {
            serde_json::Value::String(code) => match code.as_str() {
                "invalid_request" => Ok(Self::InvalidRequest),
                "organization_not_found" => Ok(Self::OrganizationNotFound),
                _ => Ok(Self::Unknown(UnknownDomainError { code, payload: None, extra: std::collections::BTreeMap::new() })),
            },
            serde_json::Value::Object(mut object) => {
                let Some(code) = object.remove("code").and_then(|value| value.as_str().map(ToOwned::to_owned)) else {
                    return Err(serde::de::Error::custom("Domain Error object is missing a string code"));
                };
                let payload = object.remove("payload");
                let extra = object.into_iter().collect::<std::collections::BTreeMap<_, _>>();
                Ok(Self::Unknown(UnknownDomainError { code, payload, extra }))
            }
            other => Err(serde::de::Error::custom(format!("Domain Error must be a string or object, got {other}"))),
        }
    }
}

pub fn encode_check_membership_request(value: &CheckMembershipRequest) -> Result<String, serde_json::Error> { encode_portable_json(value) }
pub fn decode_check_membership_request(wire: &str) -> Result<CheckMembershipRequest, serde_json::Error> { decode_portable_json(wire) }
pub fn encode_check_membership_response(value: &CheckMembershipResponse) -> Result<String, serde_json::Error> { encode_portable_json(value) }
pub fn decode_check_membership_response(wire: &str) -> Result<CheckMembershipResponse, serde_json::Error> { decode_portable_json(wire) }
pub fn encode_check_membership_error(value: &CheckMembershipError) -> Result<String, serde_json::Error> { encode_portable_json(value) }
pub fn decode_check_membership_error(wire: &str) -> Result<CheckMembershipError, serde_json::Error> { decode_portable_json(wire) }

#[doc(hidden)]
pub trait __LensoIntoOrganizationMembershipCheckMembershipResult {
    fn __lenso_into_result(self) -> Result<Result<CheckMembershipResponse, CheckMembershipError>, RuntimeFailure>;
}
impl __LensoIntoOrganizationMembershipCheckMembershipResult for Result<CheckMembershipResponse, CheckMembershipError> {
    fn __lenso_into_result(self) -> Result<Result<CheckMembershipResponse, CheckMembershipError>, RuntimeFailure> { Ok(self) }
}
impl __LensoIntoOrganizationMembershipCheckMembershipResult for Result<Result<CheckMembershipResponse, CheckMembershipError>, RuntimeFailure> {
    fn __lenso_into_result(self) -> Result<Result<CheckMembershipResponse, CheckMembershipError>, RuntimeFailure> { self }
}
impl __LensoIntoOrganizationMembershipCheckMembershipResult for Result<CheckMembershipResponse, lenso_plugin_authoring::PluginError<CheckMembershipError, RuntimeFailure>> {
    fn __lenso_into_result(self) -> Result<Result<CheckMembershipResponse, CheckMembershipError>, RuntimeFailure> {
        match self {
            Ok(value) => Ok(Ok(value)),
            Err(lenso_plugin_authoring::PluginError::Domain(error)) => Ok(Err(error)),
            Err(lenso_plugin_authoring::PluginError::Runtime(error)) => Err(error),
        }
    }
}
impl __LensoIntoOrganizationMembershipCheckMembershipResult for Result<CheckMembershipResponse, OrganizationMembershipInvocationError> {
    fn __lenso_into_result(self) -> Result<Result<CheckMembershipResponse, CheckMembershipError>, RuntimeFailure> {
        match self {
            Ok(value) => Ok(Ok(value)),
            Err(OrganizationMembershipInvocationError::Domain(error)) => Ok(Err(error)),
            Err(OrganizationMembershipInvocationError::Runtime(error)) => Err(error),
        }
    }
}

pub trait OrganizationMembershipProvider: fmt::Debug + 'static {
    fn check_membership(&self, context: InvocationContext, request: CheckMembershipRequest) -> NativeRequestFuture<OrganizationMembership>;
}

#[doc(hidden)]
#[macro_export]
macro_rules! __lenso_native_lower_organization_membership {
    ($plugin:ty, $support:path) => {
        use $support as __LensoNativeSupportOrganizationMembership;
        impl $crate::OrganizationMembershipProvider for $plugin {
        fn check_membership(&self, context: __LensoNativeSupportOrganizationMembership::InvocationContext, request: $crate::CheckMembershipRequest) -> __LensoNativeSupportOrganizationMembership::NativeRequestFuture<$crate::OrganizationMembership> {
            let plugin = self.clone();
            ::std::boxed::Box::pin(async move {
                let result = <$plugin>::check_membership(&plugin, context, request).await;
                $crate::__LensoIntoOrganizationMembershipCheckMembershipResult::__lenso_into_result(result)
            })
        }
        }
    };
}

#[derive(Debug)]
struct OrganizationMembershipRequestEndpoint { provider: Rc<dyn OrganizationMembershipProvider> }

#[derive(Debug)]
pub struct OrganizationMembershipEndpoint<P: OrganizationMembershipProvider> { provider: Rc<P>, request_endpoint: OrganizationMembershipRequestEndpoint }
impl<P: OrganizationMembershipProvider> OrganizationMembershipEndpoint<P> {
    pub fn new(provider: P) -> Self {
        let provider = Rc::new(provider);
        let request_provider: Rc<dyn OrganizationMembershipProvider> = provider.clone();
        Self { provider, request_endpoint: OrganizationMembershipRequestEndpoint { provider: request_provider } }
    }
}

impl<P: OrganizationMembershipProvider> NativeRequestEndpoint for OrganizationMembershipEndpoint<P> {
    fn capability_id(&self) -> &'static str { CAPABILITY_ID }
    fn descriptor_version(&self) -> &'static str { DESCRIPTOR_VERSION }
    fn operations(&self) -> &'static [&'static str] { &[
        CHECK_MEMBERSHIP_OPERATION,
    ] }
    fn typed_endpoint(&self) -> Option<&dyn std::any::Any> { Some(&self.request_endpoint) }
    fn invoke(&self, operation: &str, request: Box<dyn std::any::Any>, context: InvocationContext) -> LocalBoxFuture<'static, Result<Result<Box<dyn std::any::Any>, Box<dyn std::any::Any>>, RuntimeFailure>> {
        match operation {
            CHECK_MEMBERSHIP_OPERATION => {
                let Ok(request) = request.downcast::<CheckMembershipRequest>() else {
                    return Box::pin(futures::future::ready(Err(RuntimeFailure::ProtocolViolation { capability: CAPABILITY_ID })));
                };
                let invocation = Rc::clone(&self.provider).check_membership(context, *request);
                Box::pin(async move {
                    invocation.await.map(|result| {
                        result
                            .map(|value| Box::new(value) as Box<dyn std::any::Any>)
                            .map_err(|error| Box::new(error) as Box<dyn std::any::Any>)
                    })
                })
            }
            _ => Box::pin(futures::future::ready(Err(RuntimeFailure::UnknownOperation { capability: CAPABILITY_ID, operation: operation.to_owned() }))),
        }
    }
}

#[doc(hidden)]
#[macro_export]
macro_rules! __lenso_native_endpoints_organization_membership {
    ($provider:expr, $support:path) => {{
        use $support as __LensoNativeSupport;
        let endpoint = ::std::rc::Rc::new($crate::OrganizationMembershipEndpoint::new($provider));
        (
            vec![endpoint.clone() as ::std::rc::Rc<dyn __LensoNativeSupport::NativeRequestEndpoint>],
            vec![],
            vec![],
        )
    }};
}

#[doc(hidden)]
#[macro_export]
macro_rules! __lenso_native_provide_organization_membership {
    ($provider:expr, $lifecycle:expr, $support:path) => {{
        use $support as __LensoNativeSupport;
        let (request_endpoints, stream_endpoints, event_endpoints) =
            $crate::__lenso_native_endpoints_organization_membership!($provider, $support);
        __LensoNativeSupport::NativePluginInstance::with_all_endpoints(
            request_endpoints,
            stream_endpoints,
            event_endpoints,
            $lifecycle,
        )
    }};
}

#[derive(Debug)]
pub struct OrganizationMembershipClient {
    check_membership: NativeRequestHandle<OrganizationMembership>,
}
impl OrganizationMembershipClient {
    pub fn new(handle: NativeRequestHandle<OrganizationMembership>) -> Self {
        Self { check_membership: handle }
    }

    pub fn from_dependencies(dependencies: &PluginDependencies) -> Result<Self, RuntimeFailure> {
        <Self as CapabilityClient>::from_dependencies(dependencies)
    }

    pub async fn check_membership(&self, request: CheckMembershipRequest) -> Result<CheckMembershipResponse, OrganizationMembershipInvocationError> {
        self.check_membership.invoke(CHECK_MEMBERSHIP_OPERATION, request).await
            .map_err(OrganizationMembershipInvocationError::Runtime)?
            .map_err(OrganizationMembershipInvocationError::Domain)
    }

    pub async fn check_membership_with_context(&self, context: InvocationContext, request: CheckMembershipRequest) -> Result<CheckMembershipResponse, OrganizationMembershipInvocationError> {
        self.check_membership.invoke_with_context(CHECK_MEMBERSHIP_OPERATION, context, request).await
            .map_err(OrganizationMembershipInvocationError::Runtime)?
            .map_err(OrganizationMembershipInvocationError::Domain)
    }
}

impl CapabilityClient for OrganizationMembershipClient {
    type Dependencies = PluginDependencies;
    type Error = RuntimeFailure;

    const CAPABILITY_ID: &'static str = CAPABILITY_ID;
    const DESCRIPTOR_VERSION: &'static str = DESCRIPTOR_VERSION;

    fn from_dependencies(dependencies: &PluginDependencies) -> Result<Self, RuntimeFailure> {
        Ok(Self {
            check_membership: dependencies.one::<OrganizationMembership>()?,
        })
    }

    fn already_connected() -> RuntimeFailure {
        RuntimeFailure::PluginFailure {
            detail: format!("Capability Port {CAPABILITY_ID} was connected more than once"),
        }
    }
}

impl CapabilityClientMany for OrganizationMembershipClient {
    fn many_from_dependencies(
        dependencies: &PluginDependencies,
    ) -> Result<Vec<BoundCapabilityClient<Self>>, RuntimeFailure> {
        dependencies
            .bindings()
            .iter()
            .filter(|binding| binding.capability_id() == CAPABILITY_ID)
            .map(|binding| {
                Ok(BoundCapabilityClient::new(
                    binding.provider_instance(),
                    Self {
                    check_membership: binding.handle().ok_or(RuntimeFailure::Unavailable { capability: CAPABILITY_ID })?.typed::<OrganizationMembership>()?,
                    },
                ))
            })
            .collect()
    }
}

#[derive(Clone, Debug, PartialEq)]
pub enum OrganizationMembershipInvocationError {
    Domain(CheckMembershipError),
    Runtime(RuntimeFailure),
}
